apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:

  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: 'ai-service'
        metrics_path: '/metrics'
        static_configs:
        - targets: ['ai-service:8000']
        
      - job_name: 'spring-boot'
        metrics_path: '/actuator/prometheus'
        static_configs:
        - targets: ['api-gateway:8080', 'cv-service:8082']