-- CreateEnum
CREATE TYPE "TriggerType" AS ENUM ('STAGE_ENTER', 'STAGE_EXIT', 'SCORE_ABOVE', 'SCORE_BELOW', 'TIME_ELAPSED', 'MANUAL');

-- CreateEnum
CREATE TYPE "ActionType" AS ENUM ('SEND_NOTIFICATION', 'SEND_EMAIL', 'UPDATE_STATUS', 'ASSIGN_RECRUITER', 'SCHEDULE_INTERVIEW', 'AUTO_PROGRESS', 'SEND_SURVEY');
