image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Java 17
    command: |
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk
      sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> ~/.bashrc
  - name: Install Frontend Dependencies
    command: cd frontend && npm install
  - name: Start Frontend
    command: cd frontend && npm run start
  - name: Install Backend Dependencies
    command: cd backend/api-gateway && ./mvnw dependency:resolve
  - name: Start Backend (API Gateway)
    command: cd backend/api-gateway && ./mvnw spring-boot:run
  - name: Install AI-Service Dependencies
    command: cd ai-service && pip install -r requirements.txt
  - name: Start AI-Service
    command: cd ai-service && uvicorn api.main:app --host 0.0.0.0 --port 8000

ports:
  - port: 3000
    onOpen: open-browser
  - port: 8080
    onOpen: open-browser
  - port: 8000
    onOpen: open-browser