export const countries = [
    "France",
    "Belgique",
    "Suisse",
    "Canada",
    "Luxembourg",
    "Monaco",
    "Allemagne",
    "Espagne",
    "Italie",
    "Royaume-Uni",
    "Portugal",
    "Pays-Bas",
    "Maroc",
    "Algérie",
    "Tunisie",
    "Sénégal",
    "Côte d'Ivoire",
    "Mali",
    "États-Unis",
    "Brésil",
    "Argentine",
    "Mexique",
    "Chine",
    "Japon",
    "Corée du Sud",
    "Australie",
    "Nouvelle-Zélande",
    "Afrique du Sud",
    "Égypte",
    "Inde",
    // Ajoutez d'autres pays selon vos besoins
];